### PR TITLE
Cmake support

### PR DESCRIPTION
**Pull request by boryssmejda**
I modified a lot the main CMakeLists.txt file. What do you think?

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
Thanks so much for taking the time and interest in improving the library! I'll try to test and merge tomorrow!

**Review by jeremy-rifkin — CHANGES_REQUESTED** [review]
Hey @boryssmejda perhaps this will reveal how unfamiliar with cmake I am but here's my comments / questions:

What is the baseline level of cmake functionality for #3's goal of supporting cmake by the library? Looks like this would be replacing the makefile, is there a way to have both?
Currently the makefile will build both static and dynamic libraries, would that be possible to add to this?

Thanks again!

**Comment by jeremy-rifkin** [comment]
It'd be great if we could output the built library to `bin/` as well!

**Comment by boryssmejda** [comment]
> Hey @boryssmejda perhaps this will reveal how unfamiliar with cmake I am but here's my comments / questions:
> 
> What is the baseline level of cmake functionality for #3's goal of supporting cmake by the library? Looks like this would be replacing the makefile, is there a way to have both? Currently the makefile will build both static and dynamic libraries, would that be possible to add to this?
> 
> Thanks again!

When it comes to building the shared and/or static version of the library, I think that the end user should decide if it wants to use the static or shared version. It could choose either static or shared by turning off or on the option flag that are available in cmake. The flag/option would be set when calling cmake for the project. I will add this flag/option to the pull request. There is a universal variable to choose if the user wants to build static or shared library: https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html
But I think that we should have a unique flag so that the client can decide that if he has like 100 libraries and just this one particular should be shared it can do so by just setting a proper variable to true.
When it comes to the issue of keeping a makefile, I would delete it, because there is also a ninja generator and in some projects people prefer ninja that can be generated by CMake. CMake is just a built system generator and it can generate different build systems like makefiles for example. IMO, cmake provides clients of the library with the flexibility of choosing their prefered build system that they want to use.

**Comment by boryssmejda** [comment]
> It'd be great if we could output the built library to `bin/` as well!

This touches the issue of creating a package out of the library files. The package could help the clients of the library find it and link with it. I will add this point of creating a package from the library when I will upload the corrected pull request.
I will have a look at other open source libraries and check how they package their binary artifacts and public header files so that the clients can easily integrate the library into their own projects. 
Till the end of the week I will try to deliver the improved pull request :)

**Review by jeremy-rifkin — APPROVED** [review]

**Comment by jeremy-rifkin** [comment]
Thanks @boryssmejda for the explanation and for the work! Goes to show how unfamiliar I am with cmake at the moment :P I'll go ahead and merge the current changes

**Pull request merged**
